### ISSUE TITLE
Database Update Frequency

### ISSUE THREAD

**Issue by mgayheart** [MissionalDigerati/joshua_project_api#12]
This may need to be directed at JP and not the code base for the api, but it would be useful to understand the update cycle of the database that this api is pointing at. Could the documentation state something about frequency of updates? Is the api looking at the same database that is driving the live joshuaproject.net website or more like the data download on the site that has a timestamp of July? Also, is there a way to get all the people groups that have changed since a given date? Thanks!

**Comment by joshuaproject** [comment]
Micheal,

The api runs off the same db as the site.

Eric

On Friday, January 9, 2015, Michael Gayheart <notifications@github.com>
wrote:

> This may need to be directed at JP and not the code base for the api, but
> it would be useful to understand the update cycle of the database that this
> api is pointing at. Could the documentation state something about frequency
> of updates? Is the api looking at the same database that is driving the
> live joshuaproject.net website or more like the data download on the site
> that has a timestamp of July? Also, is there a way to get all the people
> groups that have changed since a given date? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MissionalDigerati/joshua_project_api/issues/12>.
>


-- 
Eric DeGrove
Joshua Project

**Comment by mgayheart** [comment]
Thanks for the quick response!
