### ISSUE TITLE
Content-Type header is incorrect

### ISSUE THREAD

**Issue by lwbcsd** [MissionalDigerati/joshua_project_api#13]
## Description

The API does not return correct content type in header.

## Context

The API response should include the correct content type header.

## Process

Example: http://api.joshuaproject.net/v1/people_groups/daily_unreached.json?api_key=xxxxxx&month=01&day=11

## Expected result

Content-Type: application/json

## Current result

Content-Type: text/html;charset=UTF-8

## Possible Fix

Set content-type to reflect the correct format.

**Comment by codemis** [comment]
@lwbcsd Thanks.  I will take a look at it.

**Comment by codemis** [comment]
This is working correctly now.  Going to close the issue.
