### ISSUE TITLE
API Documentation 'Try it out' URL is incorrect

### ISSUE THREAD

**Issue by cforbesywam** [MissionalDigerati/joshua_project_api#9]
On the API documentation page http://api.joshuaproject.net/v1/docs/available_api_requests the 'Try it out' URLs point to http://jpapi.codingstudio.org however the Getting Started info show the API URL as http://api.joshuaproject.net (which works).  None of the 'Try it out' buttons on the API Documentation page work due to the incorrect API URL and the example URL generate is also incorrect.  For example the generated url is:

http://jpapi.codingstudio.org/v1/people_groups.json?api_key=API-KEY&continents=NAR&countries=CA

but it should be:

http://api.joshuaproject.net/v1/people_groups.json?api_key=API-KEY&continents=NAR&countries=CA

**Comment by codemis** [comment]
A fix was pushed awhile ago (74e64b2957dbcd93e7e74a87740043882c086e9a), but has not been  pulled into the new site yet.  I informed Joshua Project to update their code.

**Comment by cforbesywam** [comment]
Great.  Thank you!  Colin

 

Blessings,

Colin

----------------------------------------------------------
Colin Forbes
IT Director
Youth With A Mission
Highfield Oval
Harpenden, Herts AL5 4BX

Ph. +44 (0)1582-463289
----------------------------------------------------------

Youth With A Mission Limited is registered in England & Wales
Registered Company No. 1049516, Registered Charity  No. 264078
Highfield Oval, Harpenden, Herts, AL5 4BX

**Comment by fhightower** [comment]
I was just perusing some issues and look like this one can be closed.

**Comment by codemis** [comment]
@fhightower Thank you.  I updated the code on the site, and everything works now.
